In [1]:
import pandas as pd

ipl = pd.read_csv('ipl.csv')

In [2]:
ipl.head()

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1.0,18-04-2008,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1.0,0.0,0.1,1.0,0.0,0.0,0.0,222.0
1,1.0,18-04-2008,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1.0,0.0,0.2,1.0,0.0,0.0,0.0,222.0
2,1.0,18-04-2008,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2.0,0.0,0.2,2.0,0.0,0.0,0.0,222.0
3,1.0,18-04-2008,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2.0,0.0,0.3,2.0,0.0,0.0,0.0,222.0
4,1.0,18-04-2008,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2.0,0.0,0.4,2.0,0.0,0.0,0.0,222.0

In [3]:
ipl.drop(['mid','batsman','bowler','striker','non-striker'], axis =1, inplace = True)

In [4]:
ipl.head()

,date,venue,bat_team,bowl_team,runs,wickets,overs,runs_last_5,wickets_last_5,total
0,18-04-2008,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1.0,0.0,0.1,1.0,0.0,222.0
1,18-04-2008,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1.0,0.0,0.2,1.0,0.0,222.0
2,18-04-2008,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,2.0,0.0,0.2,2.0,0.0,222.0
3,18-04-2008,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,2.0,0.0,0.3,2.0,0.0,222.0
4,18-04-2008,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,2.0,0.0,0.4,2.0,0.0,222.0

In [5]:
# We can make valid prediction only when 5 overs have passed, so removing data below 5 overs

ipl = ipl[ipl['overs']>=5.0]

#### Handling Date Column

In [6]:
# Converting date column to datetime object

from datetime import datetime
ipl['date'] = ipl['date'].apply(lambda x: datetime.strptime(x, '%d-%m-%Y'))

#### Handling Bat_team & Bowl_team Column

In [7]:
ipl.bat_team.unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Deccan Chargers', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Daredevils',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant'], dtype=object)

In [8]:
consistent_teams = ['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Daredevils', 'Sunrisers Hyderabad','Gujarat Lions','Pune Warriors']

In [9]:
ipl = ipl[(ipl['bat_team'].isin(consistent_teams)) & (ipl['bowl_team'].isin(consistent_teams))]

In [10]:
ipl['bat_team'] = ipl['bat_team'].replace({'Kings XI Punjab': 'Punjab Kings', 'Gujarat Lions': 'Gujarat Titans','Delhi Daredevils':'Delhi Capitals'})

In [11]:
ipl.bat_team.unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Punjab Kings', 'Royal Challengers Bangalore',
       'Delhi Capitals', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Titans'], dtype=object)

In [12]:
ipl['bowl_team'] = ipl['bowl_team'].replace({'Kings XI Punjab': 'Punjab Kings', 'Gujarat Lions': 'Gujarat Titans','Delhi Daredevils':'Delhi Capitals'})

In [13]:
ipl.bowl_team.unique()

array(['Royal Challengers Bangalore', 'Punjab Kings', 'Delhi Capitals',
       'Rajasthan Royals', 'Mumbai Indians', 'Chennai Super Kings',
       'Kolkata Knight Riders', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Titans'], dtype=object)

In [14]:
# One Hot Encoding for bat_team and bowl_team columns

bat_bowl = ipl[['bat_team','bowl_team']]
bat_bowl = pd.get_dummies(bat_bowl)
bat_bowl.head()

,bat_team_Chennai Super Kings,bat_team_Delhi Capitals,bat_team_Gujarat Titans,bat_team_Kolkata Knight Riders,bat_team_Mumbai Indians,bat_team_Pune Warriors,bat_team_Punjab Kings,bat_team_Rajasthan Royals,bat_team_Royal Challengers Bangalore,bat_team_Sunrisers Hyderabad,bowl_team_Chennai Super Kings,bowl_team_Delhi Capitals,bowl_team_Gujarat Titans,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Pune Warriors,bowl_team_Punjab Kings,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad
32,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
33,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
34,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
35,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
36,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [15]:
bat_bowl.drop(['bat_team_Pune Warriors','bowl_team_Pune Warriors'], axis = 1, inplace = True)
bat_bowl.head()

,bat_team_Chennai Super Kings,bat_team_Delhi Capitals,bat_team_Gujarat Titans,bat_team_Kolkata Knight Riders,bat_team_Mumbai Indians,bat_team_Punjab Kings,bat_team_Rajasthan Royals,bat_team_Royal Challengers Bangalore,bat_team_Sunrisers Hyderabad,bowl_team_Chennai Super Kings,bowl_team_Delhi Capitals,bowl_team_Gujarat Titans,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Punjab Kings,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad
32,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
33,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
34,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
35,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
36,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0

#### Handling Venue Column

In [16]:
ipl['venue'].value_counts().sort_values(ascending=False)

M Chinnaswamy Stadium                                   4962
Eden Gardens                                            4776
Wankhede Stadium                                        4711
Feroz Shah Kotla                                        4641
MA Chidambaram Stadium, Chepauk                         4008
Punjab Cricket Association Stadium, Mohali              2980
Sawai Mansingh Stadium                                  2794
Rajiv Gandhi International Stadium, Uppal               2497
Subrata Roy Sahara Stadium                              1470
Sardar Patel Stadium, Motera                            1016
Kingsmead                                               1012
Brabourne Stadium                                        933
Dr DY Patil Sports Academy                               916
Punjab Cricket Association IS Bindra Stadium, Mohali     912
Saurashtra Cricket Association Stadium                   738
SuperSport Park                                          657
Dubai International Cricket Stadium                      649
Himachal Pradesh Cricket Association Stadium             646
JSCA International Stadium Complex                       625
Sheikh Zayed Stadium                                     611
Sharjah Cricket Stadium                                  559
Shaheed Veer Narayan Singh International Stadium         555
St George's Park                                         551
New Wanderers Stadium                                    463
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium      462
Maharashtra Cricket Association Stadium                  379
Newlands                                                 374
Green Park                                               368
Barabati Stadium                                         274
Holkar Cricket Stadium                                   190
Buffalo Park                                             188
OUTsurance Oval                                          187
De Beers Diamond Oval                                     92
Name: venue, dtype: int64

In [17]:
# Venue column has multiple categorical variable so 
# we are going to use OneHoting for multiple column method

top_20 = [x for x in ipl['venue'].value_counts().sort_values(ascending=False).head(20).index]
top_20

['M Chinnaswamy Stadium',
 'Eden Gardens',
 'Wankhede Stadium',
 'Feroz Shah Kotla',
 'MA Chidambaram Stadium, Chepauk',
 'Punjab Cricket Association Stadium, Mohali',
 'Sawai Mansingh Stadium',
 'Rajiv Gandhi International Stadium, Uppal',
 'Subrata Roy Sahara Stadium',
 'Sardar Patel Stadium, Motera',
 'Kingsmead',
 'Brabourne Stadium',
 'Dr DY Patil Sports Academy',
 'Punjab Cricket Association IS Bindra Stadium, Mohali',
 'Saurashtra Cricket Association Stadium',
 'SuperSport Park',
 'Dubai International Cricket Stadium',
 'Himachal Pradesh Cricket Association Stadium',
 'JSCA International Stadium Complex',
 'Sheikh Zayed Stadium']

In [18]:
# Making 15 binary variables

import numpy as np
for label in top_20:
    ipl[label] = np.where(ipl['venue']==label,1,0)

In [19]:
ipl[['venue']+top_20].head(5)

,venue,M Chinnaswamy Stadium,Eden Gardens,Wankhede Stadium,Feroz Shah Kotla,"MA Chidambaram Stadium, Chepauk","Punjab Cricket Association Stadium, Mohali",Sawai Mansingh Stadium,"Rajiv Gandhi International Stadium, Uppal",Subrata Roy Sahara Stadium,...,Kingsmead,Brabourne Stadium,Dr DY Patil Sports Academy,"Punjab Cricket Association IS Bindra Stadium, Mohali",Saurashtra Cricket Association Stadium,SuperSport Park,Dubai International Cricket Stadium,Himachal Pradesh Cricket Association Stadium,JSCA International Stadium Complex,Sheikh Zayed Stadium
32,M Chinnaswamy Stadium,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,M Chinnaswamy Stadium,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,M Chinnaswamy Stadium,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,M Chinnaswamy Stadium,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,M Chinnaswamy Stadium,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
ipl.head(2)

,date,venue,bat_team,bowl_team,runs,wickets,overs,runs_last_5,wickets_last_5,total,...,Kingsmead,Brabourne Stadium,Dr DY Patil Sports Academy,"Punjab Cricket Association IS Bindra Stadium, Mohali",Saurashtra Cricket Association Stadium,SuperSport Park,Dubai International Cricket Stadium,Himachal Pradesh Cricket Association Stadium,JSCA International Stadium Complex,Sheikh Zayed Stadium
32,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,61.0,0.0,5.1,59.0,0.0,222.0,...,0,0,0,0,0,0,0,0,0,0
33,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,61.0,1.0,5.2,59.0,1.0,222.0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
ipl.columns

Index(['date', 'venue', 'bat_team', 'bowl_team', 'runs', 'wickets', 'overs',
       'runs_last_5', 'wickets_last_5', 'total', 'M Chinnaswamy Stadium',
       'Eden Gardens', 'Wankhede Stadium', 'Feroz Shah Kotla',
       'MA Chidambaram Stadium, Chepauk',
       'Punjab Cricket Association Stadium, Mohali', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'Subrata Roy Sahara Stadium', 'Sardar Patel Stadium, Motera',
       'Kingsmead', 'Brabourne Stadium', 'Dr DY Patil Sports Academy',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'SuperSport Park',
       'Dubai International Cricket Stadium',
       'Himachal Pradesh Cricket Association Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium'],
      dtype='object')

In [22]:
ipl.drop(['venue','bat_team', 'bowl_team','date'], axis = 1, inplace = True)
ipl.columns

Index(['runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5', 'total',
       'M Chinnaswamy Stadium', 'Eden Gardens', 'Wankhede Stadium',
       'Feroz Shah Kotla', 'MA Chidambaram Stadium, Chepauk',
       'Punjab Cricket Association Stadium, Mohali', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'Subrata Roy Sahara Stadium', 'Sardar Patel Stadium, Motera',
       'Kingsmead', 'Brabourne Stadium', 'Dr DY Patil Sports Academy',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'SuperSport Park',
       'Dubai International Cricket Stadium',
       'Himachal Pradesh Cricket Association Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium'],
      dtype='object')

#### Creating Final dataframe

In [23]:
train_ipl = pd.concat([ipl, bat_bowl], axis = 1)
train_ipl.columns

Index(['runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5', 'total',
       'M Chinnaswamy Stadium', 'Eden Gardens', 'Wankhede Stadium',
       'Feroz Shah Kotla', 'MA Chidambaram Stadium, Chepauk',
       'Punjab Cricket Association Stadium, Mohali', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'Subrata Roy Sahara Stadium', 'Sardar Patel Stadium, Motera',
       'Kingsmead', 'Brabourne Stadium', 'Dr DY Patil Sports Academy',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'SuperSport Park',
       'Dubai International Cricket Stadium',
       'Himachal Pradesh Cricket Association Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'bat_team_Chennai Super Kings', 'bat_team_Delhi Capitals',
       'bat_team_Gujarat Titans', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Punjab Kings',
       'bat_team_Rajasthan Royals', 'bat_team_Royal Challengers Bangalore',
       'bat_team_Sunrisers Hyderabad', 'bowl_team_Chennai Super Kings',
       'bowl_team_Delhi Capitals', 'bowl_team_Gujarat Titans',
       'bowl_team_Kolkata Knight Riders', 'bowl_team_Mumbai Indians',
       'bowl_team_Punjab Kings', 'bowl_team_Rajasthan Royals',
       'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad'],
      dtype='object')